
GET https://ab180-members-api-server.herokuapp.com/api/members


###
GET http://localhost:3000/api/members/3

###

POST https://ab180-members-api-server.herokuapp.com/api/members
Content-Type:application/json

[
  { 
  "name": "Sojeen Park", 
  "team": "Customer Success", 
  "position": "Team Lead", 
  "emailAddress": "sojeen@ab180.co", 
  "phoneNumber": "010-1234-5678"
  },
  { 
  "name": "Sojeen Park", 
  "team": "Customer Success", 
  "position": "Team Lead", 
  "emailAddress": "sojeen@ab180.co", 
  "phoneNumber": "010-1234-5678"
  }
]





### 
POST https://ab180-members-api-server.herokuapp.com/api/members
Content-Type:application/json

[
  { 
    "id": 15,
  "name": "Sojeen Park", 
  "team": "Customer Success", 
  "position": "Team Lead", 
  "emailAddress": "sojeen@ab180.co", 
  "phoneNumber": "010-1234-5678"
  }
]


###
POST https://ab180-members-api-server.herokuapp.com/api/members
Content-Type:application/json

[
  {
    "name": "A Yang",
    "team": "Research",
    "position": "Data Scientist",
    "emailAddress": "wonsuk@ab180.co",
    "profileImage": "profile16.png"
  }, 
  {
    "name": "C Yang",
    "team": "Research",
    "position": "Data Scientist",
    "emailAddress": "wonsuk@ab180.co",
    "profileImage": "profile16.png"
  }
]


###
POST https://ab180-members-api-server.herokuapp.com/api/members
Content-Type:application/json

[
  {
    "name": "Noel Son",
    "team": "Enablement",
    "position": "Enablement Manager",
    "emailAddress": "noel@ab180.co",
    "profileImage": "profile13.png"
  }
]


###
POST http://localhost:8000/api/members
Content-Type:application/json

[
  {
    "name": "Noel Son",
    "team": "Research",
    "position": "Data Scientist",
    "emailAddress": "wonsuk@ab180.co",
    "profileImage": "profile16.png"
  }
]

### 
DELETE https://ab180-members-api-server.herokuapp.com/api/members


###
DELETE https://ab180-members-api-server.herokuapp.com/api/members/4

###
PUT https://ab180-members-api-server.herokuapp.com/api/members/4
Content-Type:application/json

{
"name": "Wonsuk Yang"
}
